### ISSUE TITLE
Plugin replaces all Cyrillic characters with html entities

### ISSUE THREAD

**Issue by peremenov** [axe312ger/metalsmith-adaptive-images#42]
I'm using configuration like this:

```js
const images = AdaptiveImages({
  imageWidths: [1440, 960, 480],
  imageSizes: ['(min-width: 960px) 960px', '100vw'],
  defaultSize: 960,
  namingPattern: '{dir}{name}@{size}{ext}', // foo/bar-200.jpg,...
  srcsetPattern: '{url} {size}w', // foo/bar-200.jpg 200w,...
  htmlFileGlob: '**/*.html',
  htmlImageSelector: 'img',
});

...

  .use(templates({
    templateKey: 'layout',
  }))
  .use(images.replaceImages)
```

Charset of the source files utf-8. As result instead of `Зоркий` I've got `&#x417;&#x43E;&#x440;&#x43A;&#x438;&#x439;`

**Comment by axe312ger** [comment]
This is related to the internal usage of cheerio to replace the pictures and the configuration I pass: https://github.com/axe312ger/metalsmith-adaptive-images/blob/master/src/index.js#L104-L106

I had to do this to get valid HTML back then in the project I developed this for.


If anybody has a replacement for cheerio which will NOT alter the html code besides the image replacement, I'd be super happy to merge this is. A simple regex is IMHO not reliable enough.

**Comment by axe312ger** [comment]
Can you maybe try to remove the `xmlMode: true` and see if it is working properly for you? That might be a quick fix.

**Comment by peremenov** [comment]
As described [here](https://github.com/cheeriojs/cheerio/issues/866) non-safe solution could be like this:
```js
file.contents = new Buffer($.html({ decodeEntities: false }));
```
It works fine for me.

**Comment by axe312ger** [comment]
Yeah we can't do that :/

```js
var cheerio = require("cheerio")

const $ = cheerio.load('<div>&#x3C;script&#x3E;alert(&#x27;xss&#x27;)&#x3C;/script&#x3E;</div>')

console.log($.html())
// "<div>&lt;script&gt;alert(&apos;xss&apos;)&lt;/script&gt;</div>"

console.log($.html({decodeEntities: false}))
// "<div><script>alert('xss')</script></div>"
```

**Comment by peremenov** [comment]
Thank you anyways
