### ISSUE TITLE
Metalsmith CLI integration

### ISSUE THREAD

**Issue by edwardessing** [axe312ger/metalsmith-adaptive-images#6]
Hey I like the sound of this plug-in, but I'm not sure how I could integrate it if my project uses the Metalsmith CLI.

**Comment by axe312ger** [comment]
The CLI limits the configuration options a lot and this plugin has heavy configuration.

I am sorry, but I guess you need a javascript based configuration for metalsmith to get it running.

You still can run it via `node yourscript.js` from CLI 👼
